name: "[Push] Sync CI"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'src/VERSION'
      - 'docs/**'
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: cloudforet-io
  repo: actions
  ref: master

jobs:
  owner_check:
    if: github.repository_owner == 'cloudforet-io'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  master_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: owner_check
    steps:
      - name: git pull
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ${{ env.owner }}
          repo: ${{ env.repo }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ${{ env.workflow_file_name }}
          ref: ${{ env.ref }}
          wait_interval: 10
          inputs: '{"repository" : "${{ github.repository }}"}'
          trigger_workflow: true
          wait_workflow: true
  pull_workflows:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: owner_check
    steps:
      - name: git pull
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ${{ env.owner }}
          repo: ${{ env.repo }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ${{ env.workflow_file_name }}
          ref: ${{ env.ref }}
          wait_interval: 10
          inputs: '{"repository" : "${{ github.repository }}" , "sync_only" : "true"}'
          trigger_workflow: true
          wait_workflow: true
